-- =========================================================
-- SETUP COMPLETO — Comunidad BPLAY
-- Pegalo entero en el SQL Editor de Supabase. Es idempotente:
-- usa IF NOT EXISTS / DROP POLICY IF EXISTS, así que es seguro
-- correrlo aunque algunas tablas ya existan.
-- =========================================================

-- =========================================================
-- 0) HELPER: ¿el usuario actual es un AGENTE?
--    Agente = usuario autenticado y NO anónimo. Los visitantes
--    del chat usan auth anónima (is_anonymous = true).
-- =========================================================
create or replace function public.is_agent()
returns boolean language sql stable as $$
  select coalesce(
    auth.role() = 'authenticated'
    and (auth.jwt() ->> 'is_anonymous')::boolean is not true,
  false);
$$;

-- =========================================================
-- 1) contenido_dinamico
--    Rol: configuración editable del sitio sin re-deploy.
--    - Fila clave/valor 'whatsapp_num' -> número de WhatsApp vigente
--      (lo lee js/geo.js y repinta todos los wa.me / tel:).
--    - Fila slug='sorteo' -> textos/premios/fechas del sorteo
--      (lo lee js/sorteo/content.js).
--    Lectura pública; escritura solo agentes.
-- =========================================================
create table if not exists public.contenido_dinamico (
  id           bigint generated by default as identity primary key,
  -- modo clave/valor (whatsapp, etc.)
  clave        text,
  valor        text,
  -- modo "bloque" (sorteo)
  slug         text,
  is_active    boolean default true,
  kicker       text,
  titulo       text,
  premio1_label text,
  premio1_monto numeric,
  premio2_label text,
  premio2_monto numeric,
  draw_end     timestamptz,
  slots_min    int,
  slots_total  int,
  cta_label    text,
  cta_url      text,
  legal        text,
  hero_image   text
);

-- Por si la tabla ya existía con menos columnas, las agregamos:
alter table public.contenido_dinamico
  add column if not exists clave text,
  add column if not exists valor text,
  add column if not exists slug text,
  add column if not exists is_active boolean default true,
  add column if not exists kicker text,
  add column if not exists titulo text,
  add column if not exists premio1_label text,
  add column if not exists premio1_monto numeric,
  add column if not exists premio2_label text,
  add column if not exists premio2_monto numeric,
  add column if not exists draw_end timestamptz,
  add column if not exists slots_min int,
  add column if not exists slots_total int,
  add column if not exists cta_label text,
  add column if not exists cta_url text,
  add column if not exists legal text,
  add column if not exists hero_image text;

alter table public.contenido_dinamico enable row level security;

drop policy if exists contenido_public_read on public.contenido_dinamico;
create policy contenido_public_read on public.contenido_dinamico
  for select using (true);

drop policy if exists contenido_agent_write on public.contenido_dinamico;
create policy contenido_agent_write on public.contenido_dinamico
  for all using (public.is_agent()) with check (public.is_agent());

-- Seeds (solo si no existen)
insert into public.contenido_dinamico (clave, valor)
select 'whatsapp_num', '5492617490475'
where not exists (select 1 from public.contenido_dinamico where clave = 'whatsapp_num');

insert into public.contenido_dinamico
  (slug, is_active, kicker, titulo, premio1_label, premio1_monto, premio2_label, premio2_monto,
   draw_end, slots_min, slots_total, cta_label, cta_url, legal, hero_image)
select 'sorteo', true, 'SORTEO BPLAY', 'Sumá puntos y ganá',
       '1° premio', 100000, '2° premio', 50000,
       '2026-12-24T23:59:00-03:00', 160, 200,
       '¡Quiero sumar puntos!',
       'https://wa.me/5492617490475?text=Hola%2C%20quiero%20participar%20del%20SORTEO%20de%20Bplay',
       'Promoción válida para usuarios registrados y verificados, mayores de 18 años. Juego responsable.',
       'media/promos/opt/slide-sorteos.webp'
where not exists (select 1 from public.contenido_dinamico where slug = 'sorteo');

-- =========================================================
-- 2) promos
--    Rol: promociones editables sin re-deploy. La web muestra
--    solo las vigentes (active + ends_at futuro). Lo lee js/promos.js.
-- =========================================================
create table if not exists public.promos (
  id          uuid primary key default gen_random_uuid(),
  slug        text unique not null,
  title       text not null,
  subtitle    text,
  image_url   text,
  badge       text,
  wpp_text    text,
  details     jsonb,
  valid_days  text[],
  sort_order  int default 0,
  active      bool default true,
  starts_at   timestamptz,
  ends_at     timestamptz,
  created_at  timestamptz default now()
);

alter table public.promos enable row level security;

drop policy if exists promos_public_read on public.promos;
create policy promos_public_read on public.promos
  for select using (
    public.is_agent()
    or (active and (starts_at is null or starts_at <= now())
                and (ends_at  is null or ends_at  >  now()))
  );

drop policy if exists promos_agent_write on public.promos;
create policy promos_agent_write on public.promos
  for all using (public.is_agent()) with check (public.is_agent());

insert into public.promos (slug, title, badge, image_url, wpp_text, valid_days, sort_order, details) values
('joker', 'Promo Jokers', 'PROMO JOKERS 🤡', 'media/promos/opt/slide-joker.webp',
 'Hola, quiero activar la PROMO JOKERS', array['LUNES','JUEVES'], 1,
 '[{"h":"¿Cómo accedo?","p":"Hacé una carga hoy. Según el monto, recibís tiros gratis."},{"h":"Tiros por carga","list":["$20.000 → 450 tiros","$10.000 → 150 tiros","$5.000 → 50 tiros"]},{"h":"Ganancia","p":"Todo lo ganado se acredita como BONO CASINO 🎰."}]'::jsonb),
('primer-deposito', 'Primer depósito', 'PRIMER DEPÓSITO', 'media/promos/opt/slide-primer-deposito.webp',
 'Hola, quiero activar la PROMO PRIMER DEPÓSITO', array[]::text[], 2,
 '[{"h":"¿Cuál es la promo?","p":"Con tu primer depósito de $5.000 accedés a 100 tiros gratis en Joker Jewels, con ganancia retirable."},{"h":"Requisitos","list":["Usuario nuevo","Depósito mínimo $5.000"]}]'::jsonb),
('referidos', 'Promo referidos', 'PROMO REFERIDOS 🤝', 'media/promos/opt/slide-sorteos.webp',
 'Hola, quiero activar la PROMO REFERIDOS', array[]::text[], 3,
 '[{"h":"¿Cómo califica?","list":["Invitá a alguien no registrado en Bplay","Debe contactarnos antes de registrarse","Cuando deposite $5.000, recibís $10.000 para jugar"]}]'::jsonb)
on conflict (slug) do nothing;

-- =========================================================
-- 3) CHAT EN VIVO — chat_conversations + chat_messages
--    Rol: chat visitante <-> agente en tiempo real.
--    Visitante (auth anónima) solo ve/escribe SU conversación;
--    el agente ve/escribe todas.
-- =========================================================
create table if not exists public.chat_conversations (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid(),
  province    text,
  status      text not null default 'open',   -- open | agent | closed
  created_at  timestamptz default now(),
  last_at     timestamptz default now()
);

create table if not exists public.chat_messages (
  id              uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  sender          text not null check (sender in ('visitor','agent','bot')),
  body            text not null,
  created_at      timestamptz default now()
);
create index if not exists idx_chat_messages_convo on public.chat_messages(conversation_id, created_at);

alter table public.chat_conversations enable row level security;
alter table public.chat_messages      enable row level security;

drop policy if exists convo_insert on public.chat_conversations;
create policy convo_insert on public.chat_conversations
  for insert with check (user_id = auth.uid());

drop policy if exists convo_select on public.chat_conversations;
create policy convo_select on public.chat_conversations
  for select using (user_id = auth.uid() or public.is_agent());

drop policy if exists convo_update on public.chat_conversations;
create policy convo_update on public.chat_conversations
  for update using (user_id = auth.uid() or public.is_agent())
            with check (user_id = auth.uid() or public.is_agent());

drop policy if exists msg_select on public.chat_messages;
create policy msg_select on public.chat_messages
  for select using (exists (
    select 1 from public.chat_conversations c
    where c.id = conversation_id and (c.user_id = auth.uid() or public.is_agent())));

drop policy if exists msg_insert on public.chat_messages;
create policy msg_insert on public.chat_messages
  for insert with check (
    (sender = 'visitor' and exists (
      select 1 from public.chat_conversations c
      where c.id = conversation_id and c.user_id = auth.uid()))
    or (sender in ('agent','bot') and public.is_agent())
  );

-- =========================================================
-- 4) sorteo_clicks
--    Rol: métrica de clicks en el CTA del sorteo. Insert anónimo,
--    lectura solo agentes. Lo escribe js/sorteo/content.js.
-- =========================================================
create table if not exists public.sorteo_clicks (
  id         uuid primary key default gen_random_uuid(),
  page       text,
  slug       text,
  user_agent text,
  referrer   text,
  created_at timestamptz default now()
);

alter table public.sorteo_clicks enable row level security;

drop policy if exists sorteo_clicks_insert on public.sorteo_clicks;
create policy sorteo_clicks_insert on public.sorteo_clicks
  for insert with check (true);

drop policy if exists sorteo_clicks_read on public.sorteo_clicks;
create policy sorteo_clicks_read on public.sorteo_clicks
  for select using (public.is_agent());

-- =========================================================
-- 5) REALTIME — habilitar replicación de las tablas del chat
-- =========================================================
do $$ begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.chat_conversations;
exception when duplicate_object then null; end $$;

-- =========================================================
-- 6) STORAGE — bucket público para el arte de las promos
--    Rol: subir imágenes de promos sin re-deploy. Lectura
--    pública; subida solo agentes.
-- =========================================================
insert into storage.buckets (id, name, public)
values ('promos', 'promos', true)
on conflict (id) do nothing;

drop policy if exists promos_bucket_read on storage.objects;
create policy promos_bucket_read on storage.objects
  for select using (bucket_id = 'promos');

drop policy if exists promos_bucket_write on storage.objects;
create policy promos_bucket_write on storage.objects
  for all using (bucket_id = 'promos' and public.is_agent())
          with check (bucket_id = 'promos' and public.is_agent());

-- =========================================================
-- FIN. Acciones que NO son SQL (hacer en el dashboard):
--  1) Authentication → Providers → habilitar "Anonymous sign-ins".
--  2) Authentication → Users → crear el/los usuarios AGENTE.
--  3) Settings → API → rotar la SERVICE_ROLE key (estuvo en .env).
-- =========================================================
